name = "feedengage-demo-submit"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-24"

[vars]

[secrets]
#FE_API_URL
#FE_MANAGE_API_KEY
#HCAPTCHA_ACCOUNT_SECRET
